apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: "lsa33-nexus-simple"
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write

jobs:
  build-and-push:
    steps:
      - name: Checkout source code
        uses: https://github.com/cloudbees-io/checkout@v1

      - name: Configure Nexus Docker Registry credentials
        uses: https://github.com/cloudbees-io/configure-oci-credentials@v1
        id: dockerconfig
        with:
          registry: https://nexus.cloudbees.guru:8082
          username: lsa26
          password: ${{ secrets.NEXUS_PASSWORD_LSA26 }}

      - name: Build and push container image
        uses: https://github.com/cloudbees-io/kaniko@v1
        with:
          destination: nexus.cloudbees.guru:8082/unify-docker-lsa26/hackers-organized:${{ cloudbees.scm.sha }}
          tar-path: container-image.tar

      - name: Verify image push success
        uses: https://github.com/cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Docker Image Successfully Built and Pushed
            - **Repository**: nexus.cloudbees.guru:8082/unify-docker-lsa26/hackers-organized
            - **Tag**: ${{ cloudbees.scm.sha }}
            - **Full Image**: nexus.cloudbees.guru:8082/unify-docker-lsa26/hackers-organized:${{ cloudbees.scm.sha }}
          format: MARKDOWN

  test-pull:
    needs: build-and-push
    steps:
      - name: Configure Nexus Docker Registry credentials for pull test
        uses: https://github.com/cloudbees-io/configure-oci-credentials@v1
        with:
          registry: https://nexus.cloudbees.guru:8082
          username: lsa26
          password: ${{ secrets.NEXUS_PASSWORD_LSA26 }}

      - name: Test pull image from Nexus
        uses: docker://alpine:latest
        run: |
          # Install Docker CLI
          apk add --no-cache docker-cli
          
          # Test pulling the image we just pushed
          docker pull nexus.cloudbees.guru:8082/unify-docker-lsa26/hackers-organized:${{ cloudbees.scm.sha }}
          
          # Verify image exists
          docker images | grep "nexus.cloudbees.guru:8082/unify-docker-lsa26/hackers-organized"
          
          echo "✅ Successfully pulled image from Nexus registry!"

      - name: Verify pull success
        uses: https://github.com/cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Docker Image Successfully Pulled from Nexus
            - **Image**: nexus.cloudbees.guru:8082/unify-docker-lsa26/hackers-organized:${{ cloudbees.scm.sha }}
            - **Status**: ✅ Pull operation successful
            - **Registry**: Nexus Docker Repository (unify-docker-lsa26)
          format: MARKDOWN