apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Main workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write
env:
  APP_NAME: hackers-organized
  NAMESPACE: lsa33
  DOCKER_REGISTRY: nexus.cloudbees.guru:8081
  DOCKER_REPO: repository/unify-docker-lsa26
jobs:
  test:
    outputs:
      CODE_COVERAGE: ${{ steps.RunUnitTest.outputs.CODE_COVERAGE }}
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Get source code
        continue-on-error: true
      - name: Run unit tests
        id: RunUnitTest
        kind: test
        uses: docker://node:lts
        run: |
          npm ci --no-audit
          npm run test:unit
          npx jest --coverage >> $CLOUDBEES_OUTPUTS/CODE_COVERAGE
      - name: Publish test results
        uses: cloudbees-io/publish-test-results@v1
        with:
          test-type: JUnit
          folder-name: ${{ cloudbees.workspace }}/junit.xml
      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Test code coverage
            ${{ steps.RunUnitTest.outputs.CODE_COVERAGE }}
          format: MARKDOWN
          
  build-and-push-nexus:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Get source code
        kind: build
        continue-on-error: true
      # On utilisera buildkit directement dans un conteneur Node pour construire l'image
      - uses: docker://node:lts
        name: Build image directly
        run: |
          # Installation des dépendances et build de l'application
          npm ci --no-audit
          npm run build
          
          # Création d'une image minimaliste manuellement
          mkdir -p /tmp/docker-build
          cd /tmp/docker-build
          
          # Copier les fichiers nécessaires
          mkdir -p usr/share/nginx/html
          cp -r $CLOUDBEES_WORKSPACE/dist/* usr/share/nginx/html/
          
          # Créer le tarball pour Nexus
          tar -cf /tmp/image.tar ./usr
          
          # Créer un fichier de configuration minimaliste pour l'image Docker
          echo '{
            "architecture": "amd64",
            "config": {
              "Hostname": "",
              "Env": ["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],
              "Cmd": ["nginx", "-g", "daemon off;"],
              "WorkingDir": "/",
              "ExposedPorts": {"80/tcp": {}}
            },
            "rootfs": {
              "type": "layers",
              "diff_ids": []
            }
          }' > /tmp/config.json
          
          # Créer les fichiers nécessaires pour le Nexus push
          cp /tmp/image.tar $CLOUDBEES_WORKSPACE/
          cp /tmp/config.json $CLOUDBEES_WORKSPACE/
      
      # Pousser l'image vers Nexus
      - uses: docker://alpine:latest
        id: push-to-nexus
        name: Push to Nexus via CURL
        run: |
          # Ne pas arrêter immédiatement en cas d'erreur pour voir les messages d'erreur
          set +e
          apk add --no-cache curl jq tar gzip coreutils
          
          USERNAME=lsa26
          PASSWORD=${{ secrets.NEXUS_PASSWORD_LSA26 }}
          REGISTRY=${{ env.DOCKER_REGISTRY }}
          REPO_PATH=${{ env.DOCKER_REPO }}
          IMAGE_NAME=${{ env.APP_NAME }}
          TAG=${{ cloudbees.scm.sha }}
          
          # Test de connexion à Nexus
          echo "📡 Vérification de l'API Nexus..."
          if ! curl -s -f -u $USERNAME:$PASSWORD https://$REGISTRY/$REPO_PATH/v2/ > /dev/null; then
            echo "❌ Erreur: Impossible de se connecter à l'API Docker Registry"
            exit 1
          fi
          echo "✅ Connexion à l'API Docker Registry réussie"
          
          # Fonction pour calculer le digest SHA256
          sha256_digest() { sha256sum "$1" | awk '{print $1}'; }
          
          # Fonction pour pousser un blob vers Nexus
          push_blob() {
            local FILE=$1
            local DIGEST=sha256:$(sha256_digest "$FILE")
            echo "📤 Poussée du blob $FILE (SHA256:$DIGEST)..."
            
            # Vérifier si le fichier existe
            if [ ! -f "$FILE" ]; then
              echo "❌ Erreur: Le fichier $FILE n'existe pas!"
              ls -la
              return 1
            fi
            
            echo "📦 Taille du fichier: $(du -h "$FILE")"
            
            # Initialisation de l'upload
            echo "🔄 Initialisation de l'upload pour $FILE..."
            local UPLOAD_URL
            local INIT_RESPONSE
            
            INIT_RESPONSE=$(curl -v -u $USERNAME:$PASSWORD -X POST \
              "https://$REGISTRY/$REPO_PATH/v2/blobs/uploads/" 2>&1)
            
            echo "🔍 Réponse d'initialisation complète:"
            echo "$INIT_RESPONSE"
            
            UPLOAD_URL=$(echo "$INIT_RESPONSE" | grep -i "< location:" | awk '{print $3}' | tr -d '\r')
            
            if [ -z "$UPLOAD_URL" ]; then
              echo "❌ Impossible d'obtenir l'URL d'upload"
              echo "Essai avec format d'URL alternatif..."
              
              # Tentative alternative
              INIT_RESPONSE=$(curl -v -u $USERNAME:$PASSWORD -X POST \
                "https://$REGISTRY/$REPO_PATH/v2/blobs/uploads/" 2>&1)
                
              # Recherche d'autres patterns pour l'URL d'upload
              UPLOAD_URL=$(echo "$INIT_RESPONSE" | grep -i "location:" | awk '{print $2}' | tr -d '\r')
              
              if [ -z "$UPLOAD_URL" ]; then
                echo "❌ Échec: Impossible d'extraire l'URL d'upload"
                return 1
              fi
            fi
            
            echo "🔗 URL d'upload obtenue: $UPLOAD_URL"
            
            # Upload du blob
            echo "📤 Upload du blob avec l'URL: ${UPLOAD_URL}&digest=$DIGEST"
            local UPLOAD_RESPONSE
            UPLOAD_RESPONSE=$(curl -v -u $USERNAME:$PASSWORD -X PUT \
              "${UPLOAD_URL}&digest=$DIGEST" \
              --data-binary @"$FILE" 2>&1)
            
            echo "🔍 Réponse d'upload complète:"
            echo "$UPLOAD_RESPONSE"
            
            local HTTP_CODE=$(echo "$UPLOAD_RESPONSE" | grep -i "< HTTP" | awk '{print $3}')
            if [[ ! "$HTTP_CODE" =~ ^20[0-9]$ ]]; then
              echo "❌ Erreur lors de l'upload du blob: Code $HTTP_CODE"
              return 1
            fi
            
            echo "✅ Blob uploadé avec succès"
            
            # Retourner le digest sans le préfixe sha256:
            echo "${DIGEST#sha256:}"
          }
          
          # Pousser le fichier image.tar
          echo "🚀 Poussée de la couche d'image..."
          IMAGE_LAYER_DIGEST=$(push_blob image.tar)
          
          # Vérifier si le push a réussi
          if [ $? -ne 0 ]; then
            echo "❌ Échec lors de la poussée de la couche d'image"
            exit 1
          fi
          
          echo "✅ Image layer digest: $IMAGE_LAYER_DIGEST"
          
          # Pousser la configuration
          echo "🚀 Poussée de la configuration..."
          CONFIG_DIGEST=$(push_blob config.json)
          
          # Vérifier si le push a réussi
          if [ $? -ne 0 ]; then
            echo "❌ Échec lors de la poussée de la configuration"
            exit 1
          fi
          
          echo "✅ Config digest: $CONFIG_DIGEST"
          
          # Obtenir les tailles des fichiers
          CONFIG_SIZE=$(stat -c %s config.json)
          LAYER_SIZE=$(stat -c %s image.tar)
          
          # Créer le manifest
          echo "📝 Création du manifest..."
          MANIFEST_JSON="{
            \"schemaVersion\": 2,
            \"mediaType\": \"application/vnd.docker.distribution.manifest.v2+json\",
            \"config\": {
              \"mediaType\": \"application/vnd.docker.container.image.v1+json\",
              \"size\": ${CONFIG_SIZE},
              \"digest\": \"sha256:${CONFIG_DIGEST}\"
            },
            \"layers\": [
              {
                \"mediaType\": \"application/vnd.docker.image.rootfs.diff.tar.gzip\",
                \"size\": ${LAYER_SIZE},
                \"digest\": \"sha256:${IMAGE_LAYER_DIGEST}\"
              }
            ]
          }"
          
          echo "$MANIFEST_JSON" > manifest.json
          
          # Pousser le manifest
          echo "🚀 Envoi du manifest..."
          MANIFEST_RESPONSE=$(curl -v -u $USERNAME:$PASSWORD -X PUT \
            -H "Content-Type: application/vnd.docker.distribution.manifest.v2+json" \
            --data-binary @manifest.json \
            "https://$REGISTRY/$REPO_PATH/v2/manifests/${IMAGE_NAME}:${TAG}" 2>&1)
            
          echo "🔍 Réponse du manifest complète:"
          echo "$MANIFEST_RESPONSE"
          
          HTTP_CODE=$(echo "$MANIFEST_RESPONSE" | grep -i "< HTTP" | awk '{print $3}')
          if [[ ! "$HTTP_CODE" =~ ^20[0-9]$ ]]; then
            echo "❌ Erreur lors de l'envoi du manifest: Code $HTTP_CODE"
            exit 1
          fi
          
          echo "✅ Manifest envoyé avec succès"
          
          # Vérifier si l'image a été correctement poussée
          echo "🔍 Vérification de la présence de l'image..."
          VERIFY_RESPONSE=$(curl -v -u $USERNAME:$PASSWORD \
            "https://$REGISTRY/$REPO_PATH/v2/manifests/${IMAGE_NAME}:${TAG}" 2>&1)
            
          HTTP_CODE=$(echo "$VERIFY_RESPONSE" | grep -i "< HTTP" | awk '{print $3}')
          if [[ ! "$HTTP_CODE" =~ ^20[0-9]$ ]]; then
            echo "❌ Erreur: Image non trouvée après le push: Code $HTTP_CODE"
            echo "$VERIFY_RESPONSE"
            exit 1
          fi
          
          echo "✅ Image poussée avec succès: $REGISTRY/$REPO_PATH/$IMAGE_NAME:$TAG"
          
          # Sauvegarder le chemin complet de l'image pour utilisation ultérieure
          FULL_IMAGE_PATH="$REGISTRY/$REPO_PATH/$IMAGE_NAME:$TAG"
          echo "$FULL_IMAGE_PATH" > $CLOUDBEES_OUTPUTS/NEXUS_IMAGE
      
      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Built and pushed image to Nexus
            
            Image Docker poussée avec succès:
            
            **Registry**: ${{ env.DOCKER_REGISTRY }}
            **Repository**: ${{ env.DOCKER_REPO }}
            **Image**: ${{ env.APP_NAME }}:${{ cloudbees.scm.sha }}
            
            Image complète: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPO }}/${{ env.APP_NAME }}:${{ cloudbees.scm.sha }}
          format: MARKDOWN
    needs: test
  
  scan:
    outputs:
      BLOCKER_COUNT: ${{ steps.FetchSonarQubeIssues.outputs.BLOCKER_COUNT }}
      CRITICAL_COUNT: ${{ steps.FetchSonarQubeIssues.outputs.CRITICAL_COUNT }}
      MAJOR_COUNT: ${{ steps.FetchSonarQubeIssues.outputs.MAJOR_COUNT }}
      MINOR_COUNT: ${{ steps.FetchSonarQubeIssues.outputs.MINOR_COUNT }}
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Get code coverage
        kind: test
        uses: docker://node:lts
        run: |
          npm ci --no-audit
          npm run test:coverage
      - uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v1
        name: Scan with SonarQube
        kind: scan
        continue-on-error: true
        with:
          language: LANGUAGE_JS
          cover-file-name: coverage/clover.xml
          sonar-exclusion: tests/*
      - uses: cloudbees-io/snyk-sast-scan-code@v1
        name: Snyk SAST
        kind: scan
        continue-on-error: true
        with:
          orgname: ${{ secrets.SNYK_ORGNAME }}
          token: ${{ secrets.SNYK_TOKEN }}
          language: LANGUAGE_JS
      - name: Scan with Snyk SCA
        uses: cloudbees-io/snyk-sca-scan-dependency@v1
        continue-on-error: true
        with:
          orgname: ${{ secrets.SNYK_ORGNAME }}
          token: ${{ secrets.SNYK_TOKEN }}
          language: LANGUAGE_JS
      - name: Fetch SonarQube Issues
        id: FetchSonarQubeIssues
        uses: docker://alpine/git:latest
        run: |
          apk add --no-cache curl jq
          curl -u ${{ secrets.SONAR_USER }}:${{ secrets.SONAR_TOKEN }} \
          "https://sonarqube.cb-demos.io/api/issues/search?componentKeys=HackersOrganized&severities=BLOCKER,CRITICAL,MAJOR,MINOR" \
          -o sonar-issues.json
          BLOCKER_COUNT=$(jq '[.issues[] | select(.severity=="BLOCKER")] | length' sonar-issues.json)
          CRITICAL_COUNT=$(jq '[.issues[] | select(.severity=="CRITICAL")] | length' sonar-issues.json)
          MAJOR_COUNT=$(jq '[.issues[] | select(.severity=="MAJOR")] | length' sonar-issues.json)
          MINOR_COUNT=$(jq '[.issues[] | select(.severity=="MINOR")] | length' sonar-issues.json)

          echo "${BLOCKER_COUNT}" >> $CLOUDBEES_OUTPUTS/BLOCKER_COUNT
          echo "${CRITICAL_COUNT}" >> $CLOUDBEES_OUTPUTS/CRITICAL_COUNT
          echo "${MAJOR_COUNT}" >> $CLOUDBEES_OUTPUTS/MAJOR_COUNT
          echo "${MINOR_COUNT}" >> $CLOUDBEES_OUTPUTS/MINOR_COUNT
      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## SonarQube Analysis Results

            | Severity             | Issue Count |
            |----------------------|-------------|
            | BLOCKER_COUNT        | ${{ steps.FetchSonarQubeIssues.outputs.BLOCKER_COUNT }} |
            | CRITICAL_COUNT       | ${{ steps.FetchSonarQubeIssues.outputs.CRITICAL_COUNT }} |
            | MAJOR_COUNT          | ${{ steps.FetchSonarQubeIssues.outputs.MAJOR_COUNT }} |
            | MINOR_COUNT          | ${{ steps.FetchSonarQubeIssues.outputs.MINOR_COUNT }} |
          format: MARKDOWN
          
  deploy:
    environment: lsa33
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - uses: cashokannamalai/kubeconfig@v1
        name: Set kubeconfig
        with:
          secname: ${{ secrets.kubeconfig }}
      - id: install-chart
        name: Install helm chart
        uses: cloudbees-io/helm-install@v1
        with:
          chart-location: ${{ cloudbees.workspace }}/chart
          release-name: ${{ env.APP_NAME }}
          namespace: ${{ env.NAMESPACE }}
          values: |
            image:
              repository: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPO }}/${{ env.APP_NAME }}
              tag: ${{ cloudbees.scm.sha }}
            fmKey: ${{ secrets.FM_TOKEN }}
            hostname: ${{ env.APP_NAME }}-${{ env.NAMESPACE }}.preview.cb-demos.io
      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Deployed environment
            
            ✅ Application déployée avec succès!
            
            [Production frontend](https://${{ env.APP_NAME }}-${{ env.NAMESPACE }}.preview.cb-demos.io/)
            
            Image Docker: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPO }}/${{ env.APP_NAME }}:${{ cloudbees.scm.sha }}
          format: MARKDOWN
      - name: Register deployed artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPO }}/${{ env.APP_NAME }}
          version: ${{ cloudbees.scm.sha }}
          url: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPO }}/${{ env.APP_NAME }}:${{ cloudbees.scm.sha }}
          digest: ""
          target-environment: lsa33
    needs:
      - build-and-push-nexus
      - scan