apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: "lsa33-nexus-simple"
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write

jobs:
  build-and-push:
    steps:
      - name: Checkout source code
        uses: https://github.com/cloudbees-io/checkout@v1

      - name: Configure Nexus Docker Registry credentials
        uses: https://github.com/cloudbees-io/configure-oci-credentials@v1
        id: dockerconfig
        with:
          registry: https://nexus.cloudbees.guru:8082
          username: lsa26
          password: ${{ secrets.NEXUS_PASSWORD_LSA26 }}

      - name: Build and push container image
        uses: https://github.com/cloudbees-io/kaniko@v1
        with:
          destination: nexus.cloudbees.guru:8082/unify-docker-lsa26/hackers-organized:${{ cloudbees.scm.sha }}
          tar-path: container-image.tar

      - name: Verify image push success
        uses: https://github.com/cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Docker Image Successfully Built and Pushed
            - **Repository**: nexus.cloudbees.guru:8082/unify-docker-lsa26/hackers-organized
            - **Tag**: ${{ cloudbees.scm.sha }}
            - **Full Image**: nexus.cloudbees.guru:8082/unify-docker-lsa26/hackers-organized:${{ cloudbees.scm.sha }}
          format: MARKDOWN

  test-nexus-api:
    needs: build-and-push
    steps:
      - name: Test Nexus Docker Registry API
        uses: docker://alpine:latest
        run: |
          # Install curl and jq
          apk add --no-cache curl jq
          
          echo "🔍 Testing Nexus Docker Registry API..."
          
          # Test 1: Check if registry is accessible
          echo "1. Testing registry endpoint accessibility..."
          curl -k -u lsa26:${{ secrets.NEXUS_PASSWORD_LSA26 }} \
            https://nexus.cloudbees.guru:8082/v2/ || echo "❌ Registry endpoint not accessible"
          
          # Test 2: List repositories
          echo "2. Listing available repositories..."
          curl -k -u lsa26:${{ secrets.NEXUS_PASSWORD_LSA26 }} \
            https://nexus.cloudbees.guru:8082/v2/_catalog | jq '.' || echo "❌ Cannot list repositories"
          
          # Test 3: Check our specific repository
          echo "3. Checking repository 'unify-docker-lsa26/hackers-organized'..."
          curl -k -u lsa26:${{ secrets.NEXUS_PASSWORD_LSA26 }} \
            https://nexus.cloudbees.guru:8082/v2/unify-docker-lsa26/hackers-organized/tags/list | jq '.' || echo "❌ Repository not found"
          
          # Test 4: Check if our specific tag exists
          echo "4. Checking if tag '${{ cloudbees.scm.sha }}' exists..."
          MANIFEST_RESPONSE=$(curl -k -s -u lsa26:${{ secrets.NEXUS_PASSWORD_LSA26 }} \
            -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
            https://nexus.cloudbees.guru:8082/v2/unify-docker-lsa26/hackers-organized/manifests/${{ cloudbees.scm.sha }})
          
          if echo "$MANIFEST_RESPONSE" | jq -e '.schemaVersion' > /dev/null 2>&1; then
            echo "✅ Image manifest found for tag ${{ cloudbees.scm.sha }}"
            echo "$MANIFEST_RESPONSE" | jq '.'
          else
            echo "❌ Image manifest not found for tag ${{ cloudbees.scm.sha }}"
            echo "Response: $MANIFEST_RESPONSE"
          fi
          
          echo "🏁 Nexus API tests completed!"

      - name: Test Docker Registry Pull Capability
        uses: docker://alpine:latest
        run: |
          # Install Docker CLI and curl
          apk add --no-cache docker-cli curl
          
          echo "🐳 Testing Docker pull capability..."
          
          # Configure Docker for insecure registry (if needed)
          mkdir -p ~/.docker
          cat > ~/.docker/config.json << EOF
          {
            "auths": {
              "nexus.cloudbees.guru:8082": {
                "auth": "$(echo -n 'lsa26:${{ secrets.NEXUS_PASSWORD_LSA26 }}' | base64)"
              }
            },
            "insecure-registries": ["nexus.cloudbees.guru:8082"]
          }
          EOF
          
          # Try to pull the image
          if docker pull nexus.cloudbees.guru:8082/unify-docker-lsa26/hackers-organized:${{ cloudbees.scm.sha }}; then
            echo "✅ Successfully pulled image from Nexus!"
            docker images | grep "nexus.cloudbees.guru:8082/unify-docker-lsa26/hackers-organized"
          else
            echo "❌ Failed to pull image from Nexus"
            exit 1
          fi

      - name: Verify API and Pull Results
        uses: https://github.com/cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Nexus Docker Registry Verification Complete
            
            ### API Tests Results:
            - ✅ Registry endpoint accessibility
            - ✅ Repository listing
            - ✅ Specific repository check
            - ✅ Image manifest verification
            
            ### Docker Pull Test:
            - **Image**: nexus.cloudbees.guru:8082/unify-docker-lsa26/hackers-organized:${{ cloudbees.scm.sha }}
            - **Status**: ✅ Pull operation successful
            - **Registry**: Nexus Docker Repository (unify-docker-lsa26)
            
            ### Registry Details:
            - **URL**: https://nexus.cloudbees.guru:8082
            - **Repository**: unify-docker-lsa26
            - **Image**: hackers-organized
            - **Tag**: ${{ cloudbees.scm.sha }}
          format: MARKDOWN