apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Main workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write
env:
  APP_NAME: hackers-organized
  NAMESPACE: lsa33
jobs:
  test:
    outputs:
      CODE_COVERAGE: ${{ steps.RunUnitTest.outputs.CODE_COVERAGE }}
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Get source code
        continue-on-error: true
      - name: Run unit tests
        id: RunUnitTest
        kind: test
        uses: docker://node:lts
        run: |
          npm ci --no-audit
          npm run test:unit
          npx jest --coverage >> $CLOUDBEES_OUTPUTS/CODE_COVERAGE
      - name: Publish test results
        uses: cloudbees-io/publish-test-results@v1
        with:
          test-type: JUnit
          folder-name: ${{ cloudbees.workspace }}/junit.xml
      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Test code coverage
            ${{ steps.RunUnitTest.outputs.CODE_COVERAGE }}
          format: MARKDOWN
          
  build-and-push-nexus:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Get source code
        kind: build
        continue-on-error: true
      # On utilisera buildkit directement dans un conteneur Node pour construire l'image
      - uses: docker://node:lts
        name: Build image directly
        run: |
          # Installation des dépendances et build de l'application
          npm ci --no-audit
          npm run build
          
          # Création d'une image minimaliste manuellement
          mkdir -p /tmp/docker-build
          cd /tmp/docker-build
          
          # Copier les fichiers nécessaires
          mkdir -p usr/share/nginx/html
          cp -r $CLOUDBEES_WORKSPACE/dist/* usr/share/nginx/html/
          
          # Créer le tarball pour Nexus
          tar -cf /tmp/image.tar ./usr
          
          # Créer un fichier de configuration minimaliste pour l'image Docker
          echo '{
            "architecture": "amd64",
            "config": {
              "Hostname": "",
              "Env": ["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],
              "Cmd": ["nginx", "-g", "daemon off;"],
              "WorkingDir": "/",
              "ExposedPorts": {"80/tcp": {}}
            },
            "rootfs": {
              "type": "layers",
              "diff_ids": []
            }
          }' > /tmp/config.json
          
          # Créer les fichiers nécessaires pour le Nexus push
          cp /tmp/image.tar $CLOUDBEES_WORKSPACE/
          cp /tmp/config.json $CLOUDBEES_WORKSPACE/
      
      # Pousser l'image vers Nexus
      - uses: docker://alpine:latest
        id: push-to-nexus
        name: Push to Nexus via CURL
        run: |
          apk add --no-cache curl jq tar gzip coreutils
          USERNAME=lsa26
          PASSWORD=${{ secrets.NEXUS_PASSWORD_LSA26 }}
          REGISTRY=nexus.cloudbees.guru:8081
          REPO=unify-docker-lsa26
          IMAGE_NAME=hackers-organized
          TAG=${{ cloudbees.scm.sha }}
          
          # Test de connexion à Nexus
          echo "Vérification de l'API Nexus..."
          NEXUS_RESPONSE=$(curl -sS -v -u $USERNAME:$PASSWORD https://$REGISTRY/service/rest/v1/repositories 2>&1)
          echo "Réponse de Nexus: $NEXUS_RESPONSE"
          
          # Fonction pour calculer le digest SHA256
          sha256_digest() { sha256sum $1 | awk '{print $1}'; }
          
          # Fonction pour pousser un blob vers Nexus
          push_blob() {
            local FILE=$1
            local DIGEST=sha256:$(sha256_digest $FILE)
            echo "Poussée du blob $FILE (SHA256:$DIGEST)..."
            
            # Initialisation de l'upload
            echo "Initialisation de l'upload pour $FILE..."
            INIT_RESPONSE=$(curl -sS -v -u $USERNAME:$PASSWORD -X POST \
              "https://$REGISTRY/v2/$REPO/blobs/uploads/" 2>&1)
            echo "Réponse d'initialisation: $INIT_RESPONSE"
              
            UPLOAD_URL=$(echo "$INIT_RESPONSE" | grep -i Location | awk '{print $3}' | tr -d '\r')
            
            if [ -z "$UPLOAD_URL" ]; then
              echo "Impossible d'obtenir l'URL d'upload. Essai avec d'autres chemins..."
              
              # Liste tous les endpoints possibles pour comprendre la structure
              echo "Liste des endpoints Docker Registry disponibles:"
              curl -v -u $USERNAME:$PASSWORD https://$REGISTRY/v2/
              curl -v -u $USERNAME:$PASSWORD https://$REGISTRY/v2/_catalog
              
              # Essayer différents chemins
              echo "Essai avec le chemin /repository/unify-docker-lsa26/"
              INIT_RESPONSE=$(curl -sS -v -u $USERNAME:$PASSWORD -X POST \
                "https://$REGISTRY/repository/unify-docker-lsa26/v2/blobs/uploads/" 2>&1)
              UPLOAD_URL=$(echo "$INIT_RESPONSE" | grep -i Location | awk '{print $3}' | tr -d '\r')
              
              if [ -z "$UPLOAD_URL" ]; then
                echo "ERREUR: Impossible de déterminer l'URL d'upload pour Nexus"
                exit 1
              else
                echo "Chemin alternatif trouvé: /repository/unify-docker-lsa26/v2/"
                REPO="repository/unify-docker-lsa26"
              fi
            fi
            
            echo "URL d'upload obtenue: $UPLOAD_URL"
            
            # Upload du blob
            curl -sS -u $USERNAME:$PASSWORD -X PUT \
              "${UPLOAD_URL}&digest=sha256:${DIGEST}" \
              --data-binary @$FILE
            
            # Retourner le digest pour référence
            echo $DIGEST
          }
          
          # Pousser le fichier image.tar
          IMAGE_LAYER_DIGEST=$(push_blob image.tar)
          echo "Image layer digest: $IMAGE_LAYER_DIGEST"
          
          # Pousser la configuration
          CONFIG_DIGEST=$(push_blob config.json)
          echo "Config digest: $CONFIG_DIGEST"
          
          # Obtenir les tailles des fichiers
          CONFIG_SIZE=$(stat -c %s config.json)
          LAYER_SIZE=$(stat -c %s image.tar)
          
          # Créer le manifest
          echo "Création du manifest..."
          MANIFEST_JSON="{
            \"schemaVersion\": 2,
            \"mediaType\": \"application/vnd.docker.distribution.manifest.v2+json\",
            \"config\": {
              \"mediaType\": \"application/vnd.docker.container.image.v1+json\",
              \"size\": ${CONFIG_SIZE},
              \"digest\": \"sha256:${CONFIG_DIGEST}\"
            },
            \"layers\": [
              {
                \"mediaType\": \"application/vnd.docker.image.rootfs.diff.tar.gzip\",
                \"size\": ${LAYER_SIZE},
                \"digest\": \"sha256:${IMAGE_LAYER_DIGEST}\"
              }
            ]
          }"
          
          echo "$MANIFEST_JSON" > manifest.json
          
          # Pousser le manifest
          echo "Envoi du manifest..."
          MANIFEST_RESPONSE=$(curl -sS -v -u $USERNAME:$PASSWORD -X PUT \
            -H "Content-Type: application/vnd.docker.distribution.manifest.v2+json" \
            --data-binary @manifest.json \
            "https://$REGISTRY/v2/$REPO/manifests/${IMAGE_NAME}:${TAG}" 2>&1)
            
          echo "Réponse du serveur pour le manifest:"
          echo "$MANIFEST_RESPONSE"
          
          # Vérifier si l'image a été correctement poussée
          echo "Vérification de la présence de l'image..."
          curl -sS -v -u $USERNAME:$PASSWORD \
            "https://$REGISTRY/v2/$REPO/manifests/${IMAGE_NAME}:${TAG}"
          
          # Sauvegarder le chemin complet de l'image
          echo "$REGISTRY/$REPO/$IMAGE_NAME:$TAG" > $CLOUDBEES_OUTPUTS/NEXUS_IMAGE
      
      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Built and pushed image to Nexus
            
            Registry: nexus.cloudbees.guru:8081
            Repository: unify-docker-lsa26
            Image: hackers-organized:${{ cloudbees.scm.sha }}
            
            Image poussée via API REST avec curl.
          format: MARKDOWN
    needs: test
  
  scan:
    outputs:
      BLOCKER_COUNT: ${{ steps.FetchSonarQubeIssues.outputs.BLOCKER_COUNT }}
      CRITICAL_COUNT: ${{ steps.FetchSonarQubeIssues.outputs.CRITICAL_COUNT }}
      MAJOR_COUNT: ${{ steps.FetchSonarQubeIssues.outputs.MAJOR_COUNT }}
      MINOR_COUNT: ${{ steps.FetchSonarQubeIssues.outputs.MINOR_COUNT }}
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Get code coverage
        kind: test
        uses: docker://node:lts
        run: |
          npm ci --no-audit
          npm run test:coverage
      - uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v1
        name: Scan with SonarQube
        kind: scan
        continue-on-error: true
        with:
          language: LANGUAGE_JS
          cover-file-name: coverage/clover.xml
          sonar-exclusion: tests/*
      - uses: cloudbees-io/snyk-sast-scan-code@v1
        name: Synk SAST
        kind: scan
        continue-on-error: true
        with:
          orgname: ${{ secrets.SNYK_ORGNAME }}
          token: ${{ secrets.SNYK_TOKEN }}
          language: LANGUAGE_JS
      - name: Scan with Snyk SCA
        uses: cloudbees-io/snyk-sca-scan-dependency@v1
        continue-on-error: true
        with:
          orgname: ${{ secrets.SNYK_ORGNAME }}
          token: ${{ secrets.SNYK_TOKEN }}
          language: LANGUAGE_JS
      - name: Fetch SonarQube Issues
        id: FetchSonarQubeIssues
        uses: docker://alpine/git:latest
        run: |
          apk add --no-cache curl jq
          curl -u ${{ secrets.SONAR_USER }}:${{ secrets.SONAR_TOKEN }} \
          "https://sonarqube.cb-demos.io/api/issues/search?componentKeys=HackersOrganized&severities=BLOCKER,CRITICAL,MAJOR,MINOR" \
          -o sonar-issues.json
          BLOCKER_COUNT=$(jq '[.issues[] | select(.severity=="BLOCKER")] | length' sonar-issues.json)
          CRITICAL_COUNT=$(jq '[.issues[] | select(.severity=="CRITICAL")] | length' sonar-issues.json)
          MAJOR_COUNT=$(jq '[.issues[] | select(.severity=="MAJOR")] | length' sonar-issues.json)
          MINOR_COUNT=$(jq '[.issues[] | select(.severity=="MINOR")] | length' sonar-issues.json)

          echo "${BLOCKER_COUNT}" >> $CLOUDBEES_OUTPUTS/BLOCKER_COUNT
          echo "${CRITICAL_COUNT}" >> $CLOUDBEES_OUTPUTS/CRITICAL_COUNT
          echo "${MAJOR_COUNT}" >> $CLOUDBEES_OUTPUTS/MAJOR_COUNT
          echo "${MINOR_COUNT}" >> $CLOUDBEES_OUTPUTS/MINOR_COUNT
      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## SonarQube Analysis Results

            | Severity             | Issue Count |
            |----------------------|-------------|
            | BLOCKER_COUNT        | ${{ steps.FetchSonarQubeIssues.outputs.BLOCKER_COUNT }} |
            | CRITICAL_COUNT       | ${{ steps.FetchSonarQubeIssues.outputs.CRITICAL_COUNT }} |
            | MAJOR_COUNT          | ${{ steps.FetchSonarQubeIssues.outputs.MAJOR_COUNT }} |
            | MINOR_COUNT          | ${{ steps.FetchSonarQubeIssues.outputs.MINOR_COUNT }} |
          format: MARKDOWN
          
  deploy:
    environment: lsa33
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - uses: cashokannamalai/kubeconfig@v1
        name: Set kubeconfig
        with:
          secname: ${{ secrets.kubeconfig }}
      - id: install-chart
        name: Install helm chart
        uses: cloudbees-io/helm-install@v1
        with:
          chart-location: ${{ cloudbees.workspace }}/chart
          release-name: ${{ env.APP_NAME }}
          namespace: ${{ env.NAMESPACE }}
          values: |
            image:
              repository: nexus.cloudbees.guru:8081/unify-docker-lsa26/hackers-organized
              tag: ${{ cloudbees.scm.sha }}
            fmKey: ${{ secrets.FM_TOKEN }}
            hostname: ${{ env.APP_NAME }}-${{ env.NAMESPACE }}.preview.cb-demos.io
      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Deployed environment
            [Production frontend](https://${{ env.APP_NAME }}-${{ env.NAMESPACE }}.preview.cb-demos.io/)

            Running hackers-organized:${{ cloudbees.scm.sha }} from Nexus registry
          format: MARKDOWN
      - name: Register_deployed_artifact
        uses: https://github.com/cloudbees-io/register-deployed-artifact@v1
        with:
          name: nexus.cloudbees.guru:8081/unify-docker-lsa26/hackers-organized
          version: ${{ cloudbees.scm.sha }}
          url: nexus.cloudbees.guru:8081/unify-docker-lsa26/hackers-organized:${{ cloudbees.scm.sha }}
          digest: ""
          target-environment: lsa33
    needs:
      - build-and-push-nexus
      - scan