apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: psgenius-n8n-ai-agent-nodejs

on:
  workflow_dispatch:

permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write

env:
  APP_NAME: hackers-organized
  NAMESPACE: lsa33

jobs:
  build-app:
    steps:
      - name: Checkout code
        uses: cloudbees-io/checkout@v1
        with:
          fetch-depth: 1

      - name: Install and build
        uses: docker://node:lts
        run: |
          node -v
          npm ci
          npm run build
          
      - name: Send logs to n8n
        if: failure()
        uses: docker://alpine:latest
        run: |           
          curl -X POST https://your-n8n/webhook/ci-failure \
            -H "Content-Type: application/json" \
            -d '{
              "platform": "cloudbees-actions",
              "buildUrl": "'${CBA_BUILD_URL}'",
              "consoleUrl": "'${CBA_BUILD_URL}/logs'",
              "job": "'${CBA_JOB_NAME}'",
              "buildNumber": "'${CBA_RUN_ID}'"
            }'