apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: psgenius-n8n-ai-agent-nodejs
on:
  workflow_dispatch:
permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write
env:
  APP_NAME: hackers-organized
  NAMESPACE: lsa33

jobs:
  build-app:
    steps:
      - name: Checkout code
        uses: cloudbees-io/checkout@v1
        id: checkout

      - name: Install and build with full log capture
        id: build
        uses: docker://node:lts
        run: |
          # Capturer tous les logs (stdout et stderr) dans un fichier
          {
            echo "=== NODE VERSION ==="
            node -v
            npm -v
            
            echo "=== NPM INSTALL ==="
            npm ci
            
            echo "=== BUILD STARTED ==="
            npm run build
            
            echo "=== BUILD COMPLETE ==="
          } > /cloudbees/workspace/full_build.log 2>&1
          
          # Conserver le code d'erreur pour le retourner à la fin
          BUILD_EXIT_CODE=${PIPESTATUS[0]}
          exit $BUILD_EXIT_CODE

      - name: Send raw logs to n8n
        if: ${{ failure() }}
        uses: docker://curlimages/curl:latest
        run: |
          # Vérifier si le fichier de log existe
          if [ -f "/cloudbees/workspace/full_build.log" ]; then
            # Créer le payload
            echo "{\"run_id\":\"${{ cloudbees.run_id }}\",\"status\":\"failure\",\"logs\":\"$(cat /cloudbees/workspace/full_build.log | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')\"}" > /tmp/payload.json
            
            # Afficher la taille du payload
            echo "Payload size: $(wc -c < /tmp/payload.json) bytes"
            
            # Envoyer au webhook
            curl -X POST \
              -H "Content-Type: application/json" \
              -d @/tmp/payload.json \
              "https://still-elegant-asp.ngrok-free.app/webhook/ci-failure"
          else
            echo "Log file not found at /cloudbees/workspace/full_build.log"
            curl -X POST \
              -H "Content-Type: application/json" \
              -d "{\"run_id\":\"${{ cloudbees.run_id }}\",\"status\":\"failure\",\"logs\":\"Log file not found\"}" \
              "https://still-elegant-asp.ngrok-free.app/webhook/ci-failure"
          fi