apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: psgenius-n8n-ai-agent-nodejs
on:
  workflow_dispatch:
permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write
env:
  APP_NAME: hackers-organized
  NAMESPACE: lsa33
jobs:
  build-app:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Get source code
      - name: Build Node.js application
        id: BuildNodeApp
        uses: docker://node:lts
        run: |
          npm ci
          npm run build
      - name: Send failure notification
        if: ${{ failure() }}
        uses: docker://alpine:latest
        run: |
          # Installer curl dans Alpine
          apk add --no-cache curl
          
          # Créer un payload avec une valeur de timestamp fixe
          PAYLOAD="{\"job\":\"Main workflow\",\"build\":\"${{ cloudbees.run_id }}\",\"result\":\"FAILURE\",\"timestamp\":\"$(date +%s)\",\"failedStep\":\"Node.js Build\"}"
          
          echo "Envoi du payload webhook: ${PAYLOAD}"
          
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "${PAYLOAD}" \
            --connect-timeout 30 \
            https://still-elegant-asp.ngrok-free.app/webhook/ci-failure